# Generated by Django 4.0.4 on 2022-05-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0003_rename_mesure_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='conformity',
            name='comment',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='measure',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
