# Generated by Django 4.0.4 on 2022-07-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0007_alter_conformity_options_alter_measure_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4096)),
                ('conclusion', models.CharField(max_length=4096)),
                ('auditors', models.CharField(max_length=256)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('report_date', models.DateField()),
                ('type', models.CharField(choices=[('INT', 'Internal Audit'), ('CUS', 'Customer Audit'), ('NAT', 'National Authority'), ('AUD', '3rd party auditor'), ('OTHER', 'Other')], default='OTHER', max_length=5)),
                ('audited_policies', models.ManyToManyField(blank=True, to='conformity.policy')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conformity.organization')),
            ],
            options={
                'ordering': ['report_date'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=4096)),
                ('reference', models.CharField(max_length=4096)),
                ('type', models.CharField(choices=[('POS', 'Positive element'), ('OBS', 'Observation or Opportunity For Improvement'), ('MIN', 'Minor non-conformity'), ('MAJ', 'Major non-conformity'), ('CRIT', 'Critical non-conformity'), ('OTHER', 'Other remark')], default='OBS', max_length=5)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conformity.audit')),
            ],
        ),
    ]
