# Generated by Django 4.0.4 on 2022-07-09 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0009_rename_auditors_audit_auditor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finding',
            old_name='type',
            new_name='severity',
        ),
    ]
