# Generated by Django 4.1.5 on 2023-02-01 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0010_rename_type_finding_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='conclusion',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='audit',
            name='description',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='audit',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='report_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(choices=[('CRIT', 'Critical non-conformity'), ('MAJ', 'Major non-conformity'), ('MIN', 'Minor non-conformity'), ('OBS', 'Observation or Opportunity For Improvement'), ('POS', 'Positive element'), ('OTHER', 'Other remark')], default='OBS', max_length=5),
        ),
    ]
