# Generated by Django 4.1.5 on 2023-02-07 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0022_action_status_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conformity.organization'),
        ),
    ]
