# Generated by Django 4.1.6 on 2023-02-12 23:15

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0024_action_active_alter_action_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conformity',
            name='comment',
            field=tinymce.models.HTMLField(blank=True, max_length=4096),
        ),
    ]
