# Generated by Django 4.1.6 on 2023-02-13 00:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0025_alter_conformity_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='control_comment',
            field=tinymce.models.HTMLField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='action',
            name='implement_comment',
            field=tinymce.models.HTMLField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='action',
            name='plan_comment',
            field=tinymce.models.HTMLField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='action',
            name='status_comment',
            field=tinymce.models.HTMLField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='audit',
            name='conclusion',
            field=tinymce.models.HTMLField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='audit',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='finding',
            name='description',
            field=tinymce.models.HTMLField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='finding',
            name='reference',
            field=tinymce.models.HTMLField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='measure',
            name='description',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
