# Generated by Django 4.1.6 on 2023-02-14 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0027_alter_organization_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conformity',
            name='measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conformity.measure'),
        ),
        migrations.AlterField(
            model_name='conformity',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conformity.organization'),
        ),
    ]
