# Generated by Django 4.1.6 on 2023-02-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0028_alter_conformity_measure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='control_comment',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='action',
            name='description',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='action',
            name='implement_comment',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='action',
            name='plan_comment',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='action',
            name='status_comment',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='audit',
            name='conclusion',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='audit',
            name='description',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='conformity',
            name='comment',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='finding',
            name='description',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='finding',
            name='reference',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='measure',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, max_length=4096),
        ),
    ]
