# Generated by Django 4.1.6 on 2023-02-24 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conformity', '0001_squashed_0029_alter_action_control_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=4096)),
                ('frequency', models.IntegerField(choices=[('1', 'Yearly'), ('2', 'Half-Yearly'), ('4', 'Quarterly'), ('6', 'Bimonthly'), ('12', 'Monthly')], default='1')),
                ('conformity', models.ManyToManyField(blank=True, to='conformity.conformity')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ControlPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_date', models.DateField(default=django.utils.timezone.now)),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHD', 'Scheduled'), ('TOBE', 'To be evaluated'), ('OK', 'Compliant'), ('NOK', 'Non-Compliant'), ('MISS', 'Missed')], default='SCHD', max_length=4)),
                ('comment', models.TextField(blank=True, max_length=4096)),
                ('control', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conformity.control')),
                ('control_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
