# Generated by Django 4.1.6 on 2023-02-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0034_alter_controlpoint_control_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='associated_controlPoints',
            field=models.ManyToManyField(blank=True, to='conformity.controlpoint'),
        ),
    ]
