# Generated by Django 4.1.6 on 2023-02-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0036_alter_controlpoint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpoint',
            name='control_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
