# Generated by Django 4.2.9 on 2024-10-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0045_alter_attachment_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
