# Generated by Django 4.2.9 on 2024-10-13 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0047_alter_attachment_create_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='attachment',
        ),
    ]
