# Generated by Django 4.0.4 on 2022-04-20 07:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('administrative_id', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(verbose_name='Date of Publication')),
                ('version', models.IntegerField(default=0)),
                ('organization', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('N', 'Norme'), ('I', 'Internal'), ('R', 'Recomandation'), ('O', 'Other')], default='O', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=4096)),
                ('parent', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='conformity.mesure')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conformity.policy')),
            ],
        ),
        migrations.CreateModel(
            name='Conformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conformity.mesure')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conformity.organization')),
            ],
        ),
    ]
