# Generated by Django 4.1.6 on 2023-02-17 09:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('conformity', '0001_squashed_0014_mesure_is_parent'), ('conformity', '0002_rename_mesure_conformity_measure'), ('conformity', '0003_rename_mesure_measure'), ('conformity', '0004_conformity_comment_alter_measure_description'), ('conformity', '0005_alter_measure_name_alter_organization_name_and_more'), ('conformity', '0006_alter_measure_parent'), ('conformity', '0007_alter_conformity_options_alter_measure_options_and_more'), ('conformity', '0008_audit_finding'), ('conformity', '0009_rename_auditors_audit_auditor'), ('conformity', '0010_rename_type_finding_severity'), ('conformity', '0011_alter_audit_conclusion_alter_audit_description_and_more'), ('conformity', '0012_alter_audit_end_date_alter_audit_report_date_and_more'), ('conformity', '0013_alter_audit_end_date_alter_audit_report_date_and_more'), ('conformity', '0014_alter_finding_description_alter_finding_reference'), ('conformity', '0015_alter_finding_severity_alter_policy_type_action'), ('conformity', '0016_alter_action_create_date_alter_action_update_date'), ('conformity', '0017_alter_action_create_date_alter_action_update_date'), ('conformity', '0018_rename_plan_end_sate_action_plan_end_date'), ('conformity', '0019_alter_conformity_status'), ('conformity', '0020_alter_action_status'), ('conformity', '0021_alter_action_status'), ('conformity', '0022_action_status_comment'), ('conformity', '0023_alter_action_organization'), ('conformity', '0024_action_active_alter_action_status'), ('conformity', '0025_alter_conformity_comment'), ('conformity', '0026_alter_action_control_comment_and_more'), ('conformity', '0027_alter_organization_description'), ('conformity', '0028_alter_conformity_measure_and_more'), ('conformity', '0029_alter_action_control_comment_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('version', models.IntegerField(default=0)),
                ('publish_by', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('INT', 'International Standard'), ('NAT', 'National Standard'), ('TECH', 'Technical Standard'), ('RECO', 'Technical Recommendation'), ('POL', 'Internal Policy'), ('OTHER', 'Other')], default='OTHER', max_length=5)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('administrative_id', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True, max_length=4096)),
                ('applicable_policies', models.ManyToManyField(blank=True, to='conformity.policy')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=4096)),
                ('conclusion', models.TextField(blank=True, max_length=4096)),
                ('auditor', models.CharField(max_length=256)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('report_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('INT', 'Internal Audit'), ('CUS', 'Customer Audit'), ('NAT', 'National Authority'), ('AUD', '3rd party auditor'), ('OTHER', 'Other')], default='OTHER', max_length=5)),
                ('audited_policies', models.ManyToManyField(blank=True, to='conformity.policy')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conformity.organization')),
            ],
            options={
                'ordering': ['report_date'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=4096)),
                ('reference', models.TextField(blank=True, max_length=4096)),
                ('severity', models.CharField(choices=[('CRT', 'Critical non-conformity'), ('MAJ', 'Major non-conformity'), ('MIN', 'Minor non-conformity'), ('OBS', 'Opportunity For Improvement'), ('POS', 'Positive finding'), ('OTHER', 'Other remark')], default='OBS', max_length=5)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conformity.audit')),
            ],
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conformity.measure')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conformity.policy')),
                ('name', models.CharField(blank=True, max_length=50, unique=True)),
                ('level', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=1)),
                ('is_parent', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Conformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('measure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conformity.measure')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conformity.organization')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comment', models.TextField(blank=True, max_length=4096)),
                ('applicable', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('organization', 'measure')},
                'ordering': ['organization', 'measure'],
                'verbose_name': 'Conformity',
                'verbose_name_plural': 'Conformities',
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=4096)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
                ('update_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('1', 'Analysing'), ('2', 'Planning'), ('3', 'Implementing'), ('4', 'Controlling'), ('5', 'Closed'), ('7', 'Frozen'), ('9', 'Canceled')], default='1', max_length=5)),
                ('plan_start_date', models.DateField(blank=True, null=True)),
                ('plan_end_date', models.DateField(blank=True, null=True)),
                ('plan_comment', models.TextField(blank=True, max_length=4096)),
                ('implement_start_date', models.DateField(blank=True, null=True)),
                ('implement_end_date', models.DateField(blank=True, null=True)),
                ('implement_status', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('implement_comment', models.TextField(blank=True, max_length=4096)),
                ('control_date', models.DateField(blank=True, null=True)),
                ('control_comment', models.TextField(blank=True, max_length=4096)),
                ('associated_conformity', models.ManyToManyField(blank=True, to='conformity.conformity')),
                ('associated_findings', models.ManyToManyField(blank=True, to='conformity.finding')),
                ('control_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controller', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conformity.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('status_comment', models.TextField(blank=True, max_length=4096)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
