# Generated by Django 4.0.4 on 2022-05-19 21:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('conformity', '0001_initial'), ('conformity', '0002_remove_policy_pub_date_alter_mesure_parent'), ('conformity', '0003_mesure_level_mesure_lft_mesure_rght_mesure_tree_id'), ('conformity', '0004_remove_mesure_level_remove_mesure_lft_and_more'), ('conformity', '0005_mesure_level'), ('conformity', '0006_alter_mesure_name_alter_policy_type'), ('conformity', '0007_alter_policy_type'), ('conformity', '0008_rename_organization_policy_publish_by_and_more'), ('conformity', '0009_alter_organization_administrative_id_and_more'), ('conformity', '0010_conformity_responsible'), ('conformity', '0011_mesure_order'), ('conformity', '0012_alter_mesure_code_alter_mesure_description_and_more'), ('conformity', '0013_alter_policy_type'), ('conformity', '0014_mesure_is_parent')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('version', models.IntegerField(default=0)),
                ('publish_by', models.CharField(max_length=256)),
                ('type', models.CharField(choices=[('INT', 'International Standard'), ('NAT', 'National Standard'), ('TECH', 'Technical Standard'), ('RECO', 'Technical Recomandation'), ('POL', 'Internal Policy'), ('OTHER', 'Other')], default='OTHER', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Mesure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5)),
                ('title', models.CharField(blank=True, max_length=256)),
                ('description', models.CharField(blank=True, max_length=4096)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conformity.mesure')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conformity.policy')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('level', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=1)),
                ('is_parent', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('administrative_id', models.CharField(blank=True, max_length=256)),
                ('description', models.CharField(blank=True, max_length=256)),
                ('applicable_policies', models.ManyToManyField(blank=True, to='conformity.policy')),
            ],
        ),
        migrations.CreateModel(
            name='Conformity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('mesure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conformity.mesure')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conformity.organization')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
