# Generated by Django 4.0.4 on 2022-05-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0001_squashed_0014_mesure_is_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conformity',
            old_name='mesure',
            new_name='measure',
        ),
    ]
