# Generated by Django 4.0.4 on 2022-04-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0002_remove_policy_pub_date_alter_mesure_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesure',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesure',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesure',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesure',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
