# Generated by Django 4.0.4 on 2022-05-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0002_rename_mesure_conformity_measure'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mesure',
            new_name='Measure',
        ),
    ]
