# Generated by Django 4.0.4 on 2022-04-20 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0003_mesure_level_mesure_lft_mesure_rght_mesure_tree_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesure',
            name='level',
        ),
        migrations.RemoveField(
            model_name='mesure',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='mesure',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='mesure',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='mesure',
            name='name',
            field=models.CharField(default=1, editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mesure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conformity.mesure'),
        ),
    ]
