# Generated by Django 4.0.4 on 2022-04-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0004_remove_mesure_level_remove_mesure_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesure',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
