# Generated by Django 4.0.4 on 2022-05-26 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0005_alter_measure_name_alter_organization_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conformity.measure'),
        ),
    ]
