# Generated by Django 4.0.4 on 2022-04-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0005_mesure_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesure',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.CharField(choices=[('0', 'Other'), ('1', 'Norme'), ('2', 'Standard'), ('3', 'Recomandation'), ('4', 'Policy')], default='0', max_length=2),
        ),
    ]
