# Generated by Django 4.0.4 on 2022-04-24 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0007_alter_policy_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='organization',
            new_name='publish_by',
        ),
        migrations.AddField(
            model_name='organization',
            name='applicable_policies',
            field=models.ManyToManyField(to='conformity.policy'),
        ),
    ]
