# Generated by Django 4.0.4 on 2022-04-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0008_rename_organization_policy_publish_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='administrative_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='organization',
            name='applicable_policies',
            field=models.ManyToManyField(blank=True, to='conformity.policy'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
