# Generated by Django 4.0.4 on 2022-05-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0011_mesure_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesure',
            name='code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='description',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mesure',
            name='title',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
