# Generated by Django 4.1.5 on 2023-02-01 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0012_alter_audit_end_date_alter_audit_report_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audit',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
