# Generated by Django 4.0.4 on 2022-05-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0012_alter_mesure_code_alter_mesure_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.CharField(choices=[('INT', 'International Standard'), ('NAT', 'National Standard'), ('TECH', 'Technical Standard'), ('RECO', 'Technical Recomandation'), ('POL', 'Internal Policy'), ('OTHER', 'Other')], default='OTHER', max_length=5),
        ),
    ]
