# Generated by Django 4.0.4 on 2022-05-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0013_alter_policy_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesure',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
