# Generated by Django 4.1.5 on 2023-02-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0013_alter_audit_end_date_alter_audit_report_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='description',
            field=models.CharField(blank=True, max_length=4096),
        ),
        migrations.AlterField(
            model_name='finding',
            name='reference',
            field=models.CharField(blank=True, max_length=4096),
        ),
    ]
