# Generated by Django 4.1.5 on 2023-02-03 03:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conformity', '0014_alter_finding_description_alter_finding_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(choices=[('CRT', 'Critical non-conformity'), ('MAJ', 'Major non-conformity'), ('MIN', 'Minor non-conformity'), ('OBS', 'Opportunity For Improvement'), ('POS', 'Positive finding'), ('OTHER', 'Other remark')], default='OBS', max_length=5),
        ),
        migrations.AlterField(
            model_name='policy',
            name='type',
            field=models.CharField(choices=[('INT', 'International Standard'), ('NAT', 'National Standard'), ('TECH', 'Technical Standard'), ('RECO', 'Technical Recommendation'), ('POL', 'Internal Policy'), ('OTHER', 'Other')], default='OTHER', max_length=5),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=4096)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('update_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('A', 'Action under analyse'), ('P', 'Action analysed, waiting to be plan'), ('Q', 'Action planned, waiting for implementation'), ('I', 'Implementation in progress'), ('C', 'Implemented, to bo controlled'), ('S', 'Control successfully'), ('U', 'control unsuccessfully'), ('F', 'Frozen'), ('X', 'Canceled')], default='A', max_length=5)),
                ('plan_start_date', models.DateField(blank=True, null=True)),
                ('plan_end_sate', models.DateField(blank=True, null=True)),
                ('plan_comment', models.CharField(blank=True, max_length=4096)),
                ('implement_start_date', models.DateField(blank=True, null=True)),
                ('implement_end_date', models.DateField(blank=True, null=True)),
                ('implement_status', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('implement_comment', models.CharField(blank=True, max_length=4096)),
                ('control_date', models.DateField(blank=True, null=True)),
                ('control_comment', models.CharField(blank=True, max_length=4096)),
                ('associated_conformity', models.ManyToManyField(blank=True, to='conformity.conformity')),
                ('associated_findings', models.ManyToManyField(blank=True, to='conformity.finding')),
                ('control_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='controller', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conformity.organization')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
