# Generated by Django 4.1.5 on 2023-02-03 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0015_alter_finding_severity_alter_policy_type_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 23, 33, 22, 666918, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='action',
            name='update_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 3, 23, 33, 22, 666936, tzinfo=datetime.timezone.utc)),
        ),
    ]
