# Generated by Django 4.1.5 on 2023-02-03 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0016_alter_action_create_date_alter_action_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='action',
            name='update_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
