# Generated by Django 4.1.5 on 2023-02-03 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0017_alter_action_create_date_alter_action_update_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='plan_end_sate',
            new_name='plan_end_date',
        ),
    ]
