# Generated by Django 4.1.5 on 2023-02-05 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0018_rename_plan_end_sate_action_plan_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conformity',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
