# Generated by Django 4.1.5 on 2023-02-05 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0019_alter_conformity_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('A', 'Analysing'), ('P', 'Planning'), ('I', 'Implementing'), ('C', 'Controlling'), ('E', 'Close successfully'), ('F', 'Frozen'), ('X', 'Canceled')], default='A', max_length=5),
        ),
    ]
