# Generated by Django 4.1.5 on 2023-02-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0023_alter_action_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('1', 'Analysing'), ('2', 'Planning'), ('3', 'Implementing'), ('4', 'Controlling'), ('5', 'Closed'), ('7', 'Frozen'), ('9', 'Canceled')], default='1', max_length=5),
        ),
    ]
