# Generated by Django 4.1.6 on 2023-02-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0030_control_controlpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'Yearly'), (2, 'Half-Yearly'), (4, 'Quarterly'), (6, 'Bimonthly'), (12, 'Monthly')], default=1),
        ),
    ]
