# Generated by Django 4.1.6 on 2023-02-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0032_remove_control_owner_control_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpoint',
            name='control_date',
            field=models.DateField(blank=True),
        ),
    ]
