# Generated by Django 4.1.6 on 2023-03-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0037_alter_controlpoint_control_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='reference',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='control',
            name='level',
            field=models.IntegerField(choices=[(1, '1st level control'), (2, '2nd level control')], default=1),
        ),
    ]
