# Generated by Django 4.1.6 on 2023-03-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0038_action_reference_control_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='control',
            field=models.ManyToManyField(blank=True, to='conformity.control'),
        ),
    ]
