# Generated by Django 4.1.6 on 2023-03-18 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0039_control_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='level',
            field=models.IntegerField(choices=[(1, '1st level'), (2, '2nd level')], default=1),
        ),
    ]
