# Generated by Django 4.2.9 on 2024-08-25 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0040_alter_control_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Policy',
            new_name='Framework',
        ),
        migrations.AlterModelOptions(
            name='framework',
            options={'ordering': ['name'], 'verbose_name': 'Framework', 'verbose_name_plural': 'Frameworks'},
        ),
        migrations.RenameField(
            model_name='measure',
            old_name='policy',
            new_name='framework',
        ),
        migrations.RenameField(
            model_name='audit',
            old_name='audited_policies',
            new_name='audited_frameworks',
        ),
    ]
