# Generated by Django 4.2.9 on 2024-08-25 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0041_rename_policy_framework_alter_framework_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measure',
            new_name='Requirement',
        ),
        migrations.AlterModelOptions(
            name='conformity',
            options={'ordering': ['organization', 'requirement'], 'verbose_name': 'Conformity', 'verbose_name_plural': 'Conformities'},
        ),
        migrations.RenameField(
            model_name='conformity',
            old_name='measure',
            new_name='requirement',
        ),
        migrations.AlterUniqueTogether(
            name='conformity',
            unique_together={('organization', 'requirement')},
        ),
    ]
