# Generated by Django 4.2.9 on 2024-10-12 02:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0042_rename_measure_requirement_alter_conformity_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('comment', models.TextField(blank=True, max_length=4096)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('create_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
