# Generated by Django 4.2.9 on 2024-10-13 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0048_remove_finding_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='attachment',
        ),
    ]
