# Generated by Django 4.2.16 on 2025-01-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0049_remove_action_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='conformity',
            name='status_origin',
            field=models.CharField(choices=[('MAN', 'From expert statement'), ('CTRL', 'From a control'), ('IND', 'From indicator')], default='MAN', max_length=5),
        ),
    ]
