# Generated by Django 4.2.16 on 2025-07-06 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0050_conformity_status_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['status', '-update_date']},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-create_date', 'file']},
        ),
        migrations.AlterModelOptions(
            name='audit',
            options={'ordering': ['-report_date', '-start_date']},
        ),
        migrations.AlterModelOptions(
            name='control',
            options={'ordering': ['level', 'frequency', 'title']},
        ),
        migrations.AlterModelOptions(
            name='controlpoint',
            options={'ordering': ['period_end_date']},
        ),
        migrations.AlterModelOptions(
            name='finding',
            options={'ordering': ['severity']},
        ),
        migrations.RemoveField(
            model_name='conformity',
            name='status_origin',
        ),
    ]
