# Generated by Django 4.2.16 on 2025-07-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0052_framework_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='status',
            field=models.CharField(choices=[('DFT', 'Draft, not validated yet'), ('NEW', 'New and under review'), ('ACT', 'Active, actions identified and planned'), ('REJ', 'Incorrect or inadequate finding'), ('ARC', 'Archived, actions closes')], default='NEW', max_length=3),
        ),
    ]
