# Generated by Django 4.2.16 on 2025-07-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0053_finding_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finding',
            name='status',
        ),
    ]
