# Generated by Django 4.2.16 on 2025-07-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0054_remove_finding_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
