# Generated by Django 4.2.16 on 2025-08-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0055_finding_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='audit',
            name='name',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
