# Generated by Django 4.2.16 on 2025-08-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0056_audit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
