# Generated by Django 4.2.16 on 2025-08-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0057_alter_audit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='cvss',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='finding',
            name='cvss_descriptor',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='finding',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='finding',
            name='observation',
            field=models.TextField(blank=True, max_length=4096),
        ),
        migrations.AddField(
            model_name='finding',
            name='recommendation',
            field=models.TextField(blank=True, max_length=4096),
        ),
    ]
