# Generated by Django 5.2.4 on 2025-08-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0058_finding_cvss_finding_cvss_descriptor_finding_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finding',
            name='cvss',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='CVSS'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='cvss_descriptor',
            field=models.CharField(blank=True, max_length=256, verbose_name='CVSS Vector'),
        ),
        migrations.AlterField(
            model_name='finding',
            name='severity',
            field=models.CharField(choices=[('CRT', 'Critical non-conformity'), ('MAJ', 'Major non-conformity'), ('MIN', 'Minor non-conformity'), ('OBS', 'Opportunity For Improvement'), ('POS', 'Positive finding'), ('OTHER', 'Other comment')], default='OBS', max_length=5),
        ),
    ]
