# Generated by Django 5.2.4 on 2025-08-22 21:25

import django.core.validators
import django.db.models.deletion
import mptt.fields
from django.db import migrations, models

def rebuild_mptt(apps, schema_editor):
    Requirement = apps.get_model('conformity', 'Requirement')
    from mptt import register
    try:
        register(Requirement)
    except Exception:
        pass
    Requirement._tree_manager.rebuild()

class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0060_pre_MPTT_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='legacy_is_parent',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='legacy_level',
        ),
        migrations.AddField(
            model_name='requirement',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirement',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirement',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requirement',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conformity',
            name='status',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='conformity.requirement'),
        ),
        migrations.RunPython(rebuild_mptt, migrations.RunPython.noop),
    ]
