# Generated by Django 5.2.4 on 2025-08-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0061_remove_requirement_legacy_is_parent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conformity',
            options={'ordering': ['organization', 'requirement__framework', 'requirement__tree_id', 'requirement__lft'], 'verbose_name': 'Conformity', 'verbose_name_plural': 'Conformities'},
        ),
        migrations.AlterModelOptions(
            name='requirement',
            options={},
        ),
        migrations.AlterField(
            model_name='action',
            name='associated_conformity',
            field=models.ManyToManyField(blank=True, related_name='actions', to='conformity.conformity'),
        ),
        migrations.AlterField(
            model_name='action',
            name='associated_controlPoints',
            field=models.ManyToManyField(blank=True, related_name='actions', to='conformity.controlpoint'),
        ),
        migrations.AlterField(
            model_name='action',
            name='associated_findings',
            field=models.ManyToManyField(blank=True, related_name='actions', to='conformity.finding'),
        ),
    ]
