# Generated by Django 5.2.4 on 2025-08-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0062_alter_conformity_options_alter_requirement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conformity',
            name='status_justification',
            field=models.CharField(blank=True, choices=[('EXPT', 'From expert statement'), ('CTRL', 'From successful control'), ('ACT', 'From completed action'), ('FIN', 'From an audit finding'), ('CONF', 'From conformity aggregation')], default='EXPT', max_length=4),
        ),
        migrations.AddField(
            model_name='conformity',
            name='status_last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
