# Generated by Django 5.2.4 on 2025-09-03 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0063_conformity_status_justification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('goal', models.TextField(blank=True, max_length=4096)),
                ('source', models.TextField(blank=True, max_length=4096)),
                ('formula', models.TextField(blank=True, max_length=4096)),
                ('worst', models.IntegerField(default=0)),
                ('best', models.IntegerField(default=100)),
                ('warning', models.IntegerField(default=80)),
                ('critical', models.IntegerField(default=90)),
                ('frequency', models.IntegerField(choices=[(1, 'Yearly'), (2, 'Half-Yearly'), (4, 'Quarterly'), (6, 'Bimonthly'), (12, 'Monthly')], default=4)),
                ('conformity', models.ManyToManyField(blank=True, to='conformity.conformity')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conformity.organization')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_date', models.DateTimeField(blank=True, null=True)),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHD', 'Scheduled'), ('TOBE', 'To evaluate'), ('OK', 'Compliant'), ('WARN', 'Warning'), ('CRIT', 'Critical'), ('MISS', 'Missed')], default='SCHD', max_length=4)),
                ('comment', models.TextField(blank=True, max_length=4096)),
                ('value', models.IntegerField(null=True)),
                ('attachment', models.ManyToManyField(blank=True, related_name='IndicatorPoint', to='conformity.attachment')),
                ('control_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conformity.indicator')),
            ],
        ),
    ]
