# Generated by Django 5.2.7 on 2025-10-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0064_indicator_indicatorpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='conformity',
            field=models.ManyToManyField(blank=True, related_name='controls', to='conformity.conformity'),
        ),
    ]
