# Generated by Django 5.2.7 on 2026-09-24 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0068_requirement_sibling_uniqueness'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conformity',
            options={'ordering': ['organization', 'requirement__framework', 'requirement__tree_id', 'requirement__lft'], 'verbose_name': 'conformity', 'verbose_name_plural': 'conformities'},
        ),
        migrations.AlterModelOptions(
            name='framework',
            options={'ordering': ['name'], 'verbose_name': 'framework', 'verbose_name_plural': 'frameworks'},
        ),
    ]
