# Generated by Django 5.2.17 on 2026-09-27 20:33

import django.db.models.deletion
from datetime import datetime, time, timedelta
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def _day_start(value):
    result = datetime.combine(value, time.min)
    return timezone.make_aware(result, timezone.get_current_timezone())


def backfill_evidence(apps, schema_editor):
    Evidence = apps.get_model('conformity', 'Evidence')
    HumanEvidence = apps.get_model('conformity', 'HumanEvidence')
    DocumentEvidence = apps.get_model('conformity', 'DocumentEvidence')
    FindingEvidence = apps.get_model('conformity', 'FindingEvidence')
    ControlPoint = apps.get_model('conformity', 'ControlPoint')
    IndicatorPoint = apps.get_model('conformity', 'IndicatorPoint')
    Conformity = apps.get_model('conformity', 'Conformity')
    Attachment = apps.get_model('conformity', 'Attachment')
    Finding = apps.get_model('conformity', 'Finding')

    for point in ControlPoint.objects.select_related('control').iterator():
        result = {'OK': 'POS', 'NOK': 'NEG'}.get(point.status, 'NEU')
        evidence = Evidence.objects.create(
            source_type='CTRL', result=result,
            valid_from=_day_start(point.period_start_date),
            valid_to=_day_start(point.period_end_date + timedelta(days=1)),
            evaluated_at=point.control_date, evaluator_id=point.control_user_id,
            comment=point.comment,
        )
        point.evidence_id = evidence.pk
        point.save(update_fields=['evidence'])
        evidence.conformities.add(*point.control.conformity.all())
        evidence.attachments.add(*point.attachment.all())

    for point in IndicatorPoint.objects.select_related('indicator').iterator():
        result = {'OK': 'POS', 'CRIT': 'NEG'}.get(point.status, 'NEU')
        evidence = Evidence.objects.create(
            source_type='IND', result=result,
            valid_from=_day_start(point.period_start_date),
            valid_to=_day_start(point.period_end_date + timedelta(days=1)),
            evaluated_at=point.control_date, evaluator_id=point.control_user_id,
            comment=point.comment,
        )
        point.evidence_id = evidence.pk
        point.save(update_fields=['evidence'])
        evidence.conformities.add(*point.indicator.conformity.all())
        evidence.attachments.add(*point.attachment.all())

    for conformity in Conformity.objects.filter(
            status_justification='EXPT', status__isnull=False).iterator():
        result = 'POS' if conformity.status == 100 else ('NEG' if conformity.status == 0 else 'PAR')
        human = HumanEvidence.objects.create(
            source_type='HUM', result=result, decision=result,
            valid_from=conformity.status_last_update or timezone.now(),
            evaluated_at=conformity.status_last_update,
            evaluator_id=conformity.responsible_id,
            comment=conformity.comment,
        )
        human.conformities.add(conformity)

    finding_results = {'POS': 'POS', 'CRT': 'NEG', 'MAJ': 'NEG', 'MIN': 'NEG'}
    for finding in Finding.objects.select_related('audit').iterator():
        valid_from = (
            finding.audit.report_date or finding.audit.end_date
            or finding.audit.start_date or timezone.now().date()
        )
        FindingEvidence.objects.create(
            source_type='FIND', result=finding_results.get(finding.severity, 'NEU'),
            valid_from=_day_start(valid_from), finding_id=finding.pk,
            comment=finding.observation or finding.description,
        )

    for attachment in Attachment.objects.iterator():
        DocumentEvidence.objects.create(
            source_type='DOC', result='NEU',
            valid_from=attachment.create_date or timezone.now(),
            document_id=attachment.pk,
        )


def reverse_evidence(apps, schema_editor):
    apps.get_model('conformity', 'ControlPoint').objects.update(evidence=None)
    apps.get_model('conformity', 'IndicatorPoint').objects.update(evidence=None)
    apps.get_model('conformity', 'Evidence').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('conformity', '0072_attachment_sha256'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('CTRL', 'Control'), ('IND', 'Indicator'), ('HUM', 'Human assessment'), ('FIND', 'Audit finding'), ('DOC', 'Documentary proof'), ('MAN', 'Manual evidence')], max_length=4)),
                ('result', models.CharField(choices=[('POS', 'Positive'), ('NEG', 'Negative'), ('NEU', 'Neutral / inconclusive'), ('PAR', 'Partially compliant')], default='NEU', max_length=3)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result_updated_at', models.DateTimeField(default=timezone.now)),
                ('attachments', models.ManyToManyField(blank=True, related_name='evidence', to='conformity.attachment')),
            ],
            options={
                'ordering': ['-valid_from', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='conformity',
            name='evidence_state',
            field=models.CharField(choices=[('NONE', 'Not evaluated'), ('COMP', 'Compliant'), ('PART', 'Partially compliant'), ('NONC', 'Non-compliant'), ('INCO', 'Inconclusive')], default='NONE', max_length=4),
        ),
        migrations.AlterField(
            model_name='conformity',
            name='status_justification',
            field=models.CharField(blank=True, choices=[('EXPT', 'From expert statement'), ('CTRL', 'From successful control'), ('ACT', 'From completed action'), ('FIN', 'From an audit finding'), ('CONF', 'From conformity aggregation'), ('EVID', 'From evidence')], default='EXPT', max_length=4),
        ),
        migrations.CreateModel(
            name='HumanEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='conformity.evidence')),
                ('decision', models.CharField(choices=[('POS', 'Compliant'), ('PAR', 'Partially compliant'), ('NEG', 'Non-compliant')], max_length=3)),
            ],
            bases=('conformity.evidence',),
        ),
        migrations.CreateModel(
            name='ManualEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='conformity.evidence')),
                ('title', models.CharField(max_length=256)),
            ],
            bases=('conformity.evidence',),
        ),
        migrations.AddField(
            model_name='evidence',
            name='conformities',
            field=models.ManyToManyField(blank=True, related_name='evidence', to='conformity.conformity'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='evaluator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluated_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlpoint',
            name='evidence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='control_point', to='conformity.evidence'),
        ),
        migrations.AddField(
            model_name='indicatorpoint',
            name='evidence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='indicator_point', to='conformity.evidence'),
        ),
        migrations.CreateModel(
            name='DocumentEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='conformity.evidence')),
                ('title', models.CharField(blank=True, max_length=256)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_evidence', to='conformity.attachment')),
            ],
            bases=('conformity.evidence',),
        ),
        migrations.CreateModel(
            name='FindingEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='conformity.evidence')),
                ('finding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_record', to='conformity.finding')),
            ],
            bases=('conformity.evidence',),
        ),
        migrations.RunPython(backfill_evidence, reverse_evidence),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__isnull', True), ('valid_to__gt', models.F('valid_from')), _connector='OR'), name='chk_evidence_positive_validity'),
        ),
    ]
