name: Pylint
permissions:
  contents: read

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install project dependencies
      run: |
        pip install -r requirements.txt
    - name: Install pylint
      run: |
        python -m pip install --upgrade pip
        pip install pylint-django
    - name: Analysing the code with pylint
      run: |
        pylint -E --load-plugins pylint_django --django-settings-module=oxomium --ignore-paths='.*/migrations/' --ignore=__init__.py,manage.py $(git ls-files '*.py')
